version: "3.8" # version del compose file
services:
  web: # servicio web que hemos configurado en el dockerfile (php + apache)
    container_name: web
    build: .
    volumes:
      - ./public_html:/var/www/html
    ports:
      - 80:80
  db: # servicio de la base de datos (mysql)
    container_name: mysql_db
    image: mysql:8.1
    volumes: 
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: notas_db
    ports:
      - 3306:3306